bond_lengths = {
    'CYS': [
        ['CB', 'SG']
        ],
    'GLN': [
        ['CB', 'CG'],
        ['CG', 'CD'],
        ['CD', 'OE1'],
        ['CD', 'NE2']
        ],
    'ILE': [
        ['CB', 'CG1'],
        ['CG1', 'CD1'],
        ['CB', 'CG2']],
    'SER': [
        ['CB', 'OG']],
    'VAL': [
        ['CB', 'CG1'],
        ['CB', 'CG2']],
    'LYS': [
        ['CB', 'CG'],
        ['CG', 'CD'],
        ['CD', 'CE'],
        ['CE', 'NZ']],
    'PRO': [
        ['CB', 'CG'],
        ['CG', 'CD'],
        ['CD', 'N']],
    'THR': [
        ['CB', 'OG1'],
        ['CB', 'CG2']],
    'PHE': [
        ['CB', 'CG'],
        ['CG', 'CD1'],
        ['CG', 'CD2'],
        ['CD1', 'CE1'],
        ['CD2', 'CE2'],
        ['CZ', 'CE1'],
        ['CZ', 'CE2']],
    'GLU': [
        ['CB', 'CG'],
        ['CG', 'CD'],
        ['CD', 'OE1'],
        ['CD', 'OE2']],
    'HIS': [
        ['CB', 'CG'],
        ['CG', 'ND1'],
        ['ND1', 'CE1'],
        ['CE1', 'NE2'],
        ['NE2', 'CD2'],
        ['CG', 'CD2']],
    'MET': [
        ['CB', 'CG'],
        ['CG', 'SD'],
        ['SD', 'CE']],
    'ASP': [
        ['CB', 'CG'],
        ['CG', 'OD1'],
        ['CG', 'OD2']],
    'LEU': [
        ['CB', 'CG'],
        ['CG', 'CD1'],
        ['CG', 'CD2']],
    'ARG': [
        ['CB', 'CG'],
        ['CG', 'CD'],
        ['CD', 'NE'],
        ['NE', 'CZ'],
        ['CZ', 'NH1'],
        ['CZ', 'NH2']],
    'TRP': [
        ['CB', 'CG'],
        ['CG', 'CD1'],
        ['CD1', 'NE1'],
        ['NE1', 'CE2'],
        ['CE2', 'CZ2'],
        ['CZ2', 'CH2'],
        ['CH2', 'CZ3'],
        ['CZ3', 'CE3'],
        ['CD2', 'CE3'],
        ['CG', 'CD2'],
        ['CD2', 'CE2']],
    'ASN': [
        ['CB', 'CG'],
        ['CG', 'OD1'],
        ['CG', 'ND2']],
    'TYR': [
        ['CB', 'CG'],
        ['CG', 'CD1'],
        ['CG', 'CD2'],
        ['CD1', 'CE1'],
        ['CD2', 'CE2'],
        ['CZ', 'CE1'],
        ['CZ', 'CE2'],
        ['CZ', 'OH']]
    }


bond_angles = {
    'CYS': [
        ['CA', 'CB', 'SG']],
    'GLN': [
        ['CA', 'CB', 'CG'],
        ['CB', 'CG', 'CD'],
        ['CG', 'CD', 'OE1'],
        ['CG', 'CD', 'NE2'],
        ['OE1', 'CD', 'NE2']],
    'ILE': [
        ['CA', 'CB', 'CG2'],
        ['CA', 'CB', 'CG1'],
        ['CG1', 'CB', 'CG2'],
        ['CB', 'CG1', 'CD1']],
    'SER': [
        ['CA', 'CB', 'OG']],
    'VAL': [
        ['CA', 'CB', 'CG1'],
        ['CA', 'CB', 'CG2'],
        ['CG1', 'CB', 'CG2']],
    'LYS': [
        ['CA', 'CB', 'CG'],
        ['CB', 'CG', 'CD'],
        ['CG', 'CD', 'CE'],
        ['CD', 'CE', 'NZ']],
    'PRO': [
        ['CA', 'CB', 'CG'],
        ['CB', 'CG', 'CD'],
        ['CG', 'CD', 'N'],
        ['CD', 'N', 'CA']],
    'THR': [
        ['CA', 'CB', 'OG1'],
        ['CA', 'CB', 'CG2'],
        ['OG1', 'CB', 'CG2']], 
    'PHE': [
        ['CA', 'CB', 'CG'],
        ['CB', 'CG', 'CD1'],
        ['CB', 'CG', 'CD2'],
        ['CD1', 'CG', 'CD2'],
        ['CE1', 'CZ', 'CE2'],
        ['CG', 'CD1', 'CE1'],
        ['CG', 'CD2', 'CE2'],
        ['CZ', 'CE1', 'CD1'],
        ['CZ', 'CE2', 'CD2']],
    'GLU': [
        ['CA', 'CB', 'CG'],
        ['CB', 'CG', 'CD'],
        ['CG', 'CD', 'OE1'],
        ['CG', 'CD', 'OE2'],
        ['OE1', 'CD', 'OE2']],
    'HIS': [
        ['CA', 'CB', 'CG'],
        ['CB', 'CG', 'CD2'],
        ['CB', 'CG', 'ND1'],
        ['ND1', 'CG', 'CD2'],
        ['CG', 'ND1', 'CE1'],
        ['ND1', 'CE1', 'NE2'],
        ['CE1', 'NE2', 'CD2'],
        ['CG', 'CD2', 'NE2']],
    'MET': [
        ['CA', 'CB', 'CG'],
        ['CB', 'CG', 'SD'],
        ['CG', 'SD', 'CE']],
    'ASP': [
        ['CA', 'CB', 'CG'],
        ['CB', 'CG', 'OD1'],
        ['CB', 'CG', 'OD2'],
        ['OD1', 'CG', 'OD2']],
    'LEU': [
        ['CA', 'CB', 'CG'],
        ['CB', 'CG', 'CD1'],
        ['CB', 'CG', 'CD2'],
        ['CD1', 'CG', 'CD2']],
    'ARG': [
        ['CA', 'CB', 'CG'],
        ['CB', 'CG', 'CD'],
        ['CG', 'CD', 'NE'],
        ['CD', 'NE', 'CZ'],
        ['NE', 'CZ', 'NH1'],
        ['NE', 'CZ', 'NH2'],
        ['NH1', 'CZ', 'NH2']],
    'TRP': [
        ['CA', 'CB', 'CG'],
        ['CB', 'CG', 'CD1'],
        ['CB', 'CG', 'CD2'],
        ['CD2', 'CG', 'CD1'],
        ['CG', 'CD1', 'NE1'],
        ['CD1', 'NE1', 'CE2'],
        ['NE1', 'CE2', 'CD2'],
        ['CG', 'CD2', 'CE2'],
        ['CE2', 'CD2', 'CE3'],
        ['CD2', 'CE2', 'CZ2'],
        ['CE2', 'CZ2', 'CH2'],
        ['CZ2', 'CH2', 'CZ3'],
        ['CE3', 'CZ3', 'CH2'],
        ['CD2', 'CE3', 'CZ3'],
        ['CG', 'CD2', 'CE3'],
        ['NE1', 'CE2', 'CZ2']],
    'ASN': [
        ['CA', 'CB', 'CG'],
        ['CB', 'CG', 'OD1'],
        ['CB', 'CG', 'ND2'],
        ['OD1', 'CG', 'ND2']],
    'TYR': [
        ['CA', 'CB', 'CG'],
        ['CB', 'CG', 'CD1'],
        ['CB', 'CG', 'CD2'],
        ['CD1', 'CG', 'CD2'],
        ['CE1', 'CZ', 'CE2'],
        ['CG', 'CD1', 'CE1'],
        ['CG', 'CD2', 'CE2'],
        ['CZ', 'CE1', 'CD1'],
        ['CZ', 'CE2', 'CD2'],
        ['CE1', 'CZ', 'OH'],
        ['CE2', 'CZ', 'OH']]
    }

sidechain_angle_list = [
    'CD1_CE1_CZ',
    'ND2_CG_OD1',
    'ND2_CG_CB',
    'OE1_CD_CG',
    'NE2_CD2_CG',
    'NH2_CZ_NE',
    'NE1_CD1_CG',
    'OD2_CG_CB',
    'OE2_CD_OE1',
    'CZ3_CE3_CD2',
    'NE2_CD_OE1',
    'CZ2_CE2_CD2',
    'CE2_CD2_CG',
    'NE2_CE1_ND1',
    'OE2_CD_CG',
    'CD2_NE2_CE1',
    'CE_CD_CG',
    'NH2_CZ_NH1',
    'N_CD_CG',
    'CH2_CZ2_CE2',
    'CD2_CE2_NE1',
    'OG_CB_CA',
    'NE_CD_CG',
    'CG_CB_CA',
    'CZ2_CE2_NE1',
    'CE_SD_CG',
    'CG2_CB_OG1',
    'CZ_NE_CD',
    'OD2_CG_OD1',
    'CG2_CB_CG1',
    'CD2_CG_ND1',
    'CE3_CD2_CE2',
    'NE2_CD_CG',
    'CE2_NE1_CD1',
    'OH_CZ_CE2',
    'OH_CZ_CE1',
    'CD2_CE2_CZ',
    'CD1_CG_CB',
    'CE1_CD1_CG',
    'CD1_CG1_CB',
    'SD_CG_CB',
    'CZ3_CH2_CZ2',
    'OD1_CG_CB',
    'CD1_CG_CD2',
    'CE2_CZ_CE1',
    'CG2_CB_CA',
    'CH2_CZ3_CE3',
    'SG_CB_CA',
    'CD_CG_CB',
    'CD2_CG_CD1',
    'ND1_CG_CB',
    'NH1_CZ_NE',
    'NZ_CE_CD',
    'CE1_ND1_CG',
    'CE3_CD2_CG',
    'CA_N_CD',
    'OG1_CB_CA',
    'CD2_CG_CB',
    'CG1_CB_CA']

sidechain_length_list = [
    'OE2_CD',
    'SG_CB',
    'NZ_CE',
    'CZ3_CH2',
    'CG_CB',
    'N_CD',
    'CD2_NE2',
    'CE3_CD2',
    'OG_CB',
    'CE1_ND1',
    'OD2_CG',
    'NE2_CD',
    'SD_CG',
    'CZ_NE',
    'CE1_CZ',
    'NH1_CZ',
    'CD1_CG',
    'CG1_CB',
    'OD1_CG',
    'CE3_CZ3',
    'CD1_CG1',
    'NE2_CE1',
    'CD_CG',
    'CG2_CB',
    'CE_CD',
    'ND1_CG',
    'CE2_NE1',
    'CE2_CD2',
    'NE_CD',
    'CE2_CZ',
    'NH2_CZ',
    'OH_CZ',
    'CD2_CG',
    'CE_SD',
    'OE1_CD',
    'NE1_CD1',
    'CE1_CD1',
    'ND2_CG',
    'CH2_CZ2',
    'OG1_CB',
    'CZ2_CE2']
